<nav>
                <i class='bx bx-menu' ></i>
                <a href="#" class="nav-link"></a>
                <form action="#">
                    <div class="form-input">
                        <input type="search" placeholder="Searching for tour...">
                        <button type="submit" class="search-btn"><i class='bx bx-search' ></i></button>
                    </div>
                </form>
                <input type="checkbox" id="switch-mode" hidden>
                <label for="switch-mode" class="switch-mode"></label>


                <!-- Notification Dropdown -->
                <a href="javascript:void(0)" class="notification" role="button" onclick="toggleDropdown(event)">
                    <i class='bx bxs-bell'></i>
                </a>

                <div id="notificationDropdown" class="dropdown hidden">
                    <h2>Notifications</h2>
                    <div class="dropdown-content">
                        <!-- Content will be dynamically generated by JavaScript -->
                    </div>
                    <a href="notifications" class="see-more"><button >See previous notifications</button></a>
                </div>

                <div id="toastContainer" data-message="Welcome back! You have new notifications."></div>
                <div class="image-container">
                    <img src="${user.avatar}" alt="User Avatar" class="avatar" style="width: 80%; height: auto;">
                </div>

            </nav>